# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html

# Logo Image Source
logo_src: /images/logo.svg

# Theme Main Subtitle
subtitle_main: Kris's Internet Website.

# Theme Secondary subtitle
susbtitle_secondary: Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.

# Footer About Section
about_footer: This site's theme is Hexo by <a href="http://www.codeblocq.com/" target="_blank">Jonathan Klughertz</a>.<br />.

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/indiec0re
facebook_url: 
instagram_url: 
dribble_url: 
github_url: https://github.com/indiecore
googleplus_url:
behance_url:
fivehundredpx_url:
email_url: mailto:kris@krisgee.com
rss_url:
