# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Logo Image Source
logo_src: /images/KG-Logo-144.png

# Theme Main Subtitle
subtitle_main: Kris's Internet Website

# Theme Secondary subtitle
subtitle_secondary: Kristopher is a game developer with a specialization in Unity & Mobile app development

# Footer About Section
about_footer: This theme was initially developed by HTML5 Templates and adapted for Hexo by Jonathan Klughertz.

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates: true

# Google Analytics Tracking ID
google_analytics: UA-36939211-1

# Social Accounts
github_url: https://github.com/indiecore
email_url: mailto:kris@krisgee.com
twitter_url: https://twitter.com/indiec0re
linkedin_url: https://www.linkedin.com/in/kristopher-gay-4590107a/
facebook_url: 
instagram_url: 
dribble_url: 
googleplus_url:
behance_url:
fivehundredpx_url:
rss_url:
